name: Database Backup

on:
  schedule:
    - cron: '30 16 * * *'   # 10 PM IST
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install PostgreSQL 17
        run: |
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17

      - name: Backup database
        run: |
          pg_dump "${{ secrets.DATABASE_URL }}" > backup.sql

      - name: Zip backup
        run: |
          zip backup_$(date +%F).zip backup.sql

      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: database-backup
          path: backup_*.zip