name: Database Backup

on:
  schedule:
    - cron: '30 16 * * *'   # 10 PM IST
  workflow_dispatch:

jobs:
  backup:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install PostgreSQL 17 Client
        run: |
          sudo apt-get update
          sudo apt-get install -y wget gnupg
          wget -qO - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo gpg --dearmor -o /usr/share/keyrings/postgresql.gpg
          echo "deb [signed-by=/usr/share/keyrings/postgresql.gpg] http://apt.postgresql.org/pub/repos/apt noble-pgdg main" | sudo tee /etc/apt/sources.list.d/pgdg.list
          sudo apt-get update
          sudo apt-get install -y postgresql-client-17

      - name: Backup database
        run: |
          /usr/lib/postgresql/17/bin/pg_dump "${{ secrets.DATABASE_URL }}" > backup.sql

      - name: Zip backup
        run: |
          zip backup_$(date +%F).zip backup.sql

      - name: Upload backup artifact
        uses: actions/upload-artifact@v4
        with:
          name: database-backup
          path: backup_*.zip